### ISSUE TITLE
Ingest inspection results to SLIMM directly through their API

### ISSUE THREAD

**Issue by vetlek** [equinor/isar#73]
Currently all the inspections results are uploaded on the end of the mission when we enter cancel. This can be problematic if the mission is very long and we want the results as fast as possible (no need to get all inspections at the same time). If the state machine crashes due to internal or external issues, the inspection results are potentially lost. A potential fix is to upload the results in the collect state.

**Comment by aestene** [comment]
Note that there are requirements for a continuous internet connection by making this change. This is to some extent already required, so it may not be much of a concern. 

The upload now is also dependent on the full format of the mission. Meaning it is easier to know all the results when uploading than to do one-by-one. It is not impossible to implement however.

**Comment by aestene** [comment]
Due to the nature of the final result which should be updated and the fact that the upload is not valid before the final package is put together it may be that the current solution is preferred. However, we may perform download in collect and try to use a local file cache for storing the files until they should be uploaded. 

In case of a mission failing all the collected results may be uploaded at the end.
